AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Skills Resume API Function

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: nodejs18.x

Resources:

  MyResumeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  ResumeApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: resume-experience-Moira   # Replace "guillermo" with your name
      Policies:
        - DynamoDBReadPolicy:
            TableName: resume-experience-Moira  # Replace "guillermo" with your name
      Events:
        GetExperience:
          Type: Api
          Properties:
            RestApiId: !Ref MyResumeApi
            Path: /experiences
            Method: GET

